---
title: "FML ASSIGNMENT 1-811296474"
output: html_document
date: "2023-09-09"
---
#Step1: Importing the data
#Source of Dataset:https://www.kaggle.com/datasets/gadigevishalsai/sachin-tendulkar-100-centuries
```{r}
bhargav1<-read.csv("C:/Users/BHARGAV/OneDrive/Desktop/The Dataset.csv")
bhargav1
```
#Step2: Descriptive Statistics for Quantitative variables

```{r}

summary(bhargav1)
```
```{r}
mean(bhargav1$Runs.Scored)
```


```{r}
median(bhargav1$Runs.Scored)
```


```{r}
sum(bhargav1$Runs.Scored)
```


```{r}
sd(bhargav1$Runs.Scored)
```


```{r}
var(bhargav1$Runs.Scored)
```


```{r}
max(bhargav1$Runs.Scored)
```


```{r}
min(bhargav1$Runs.Scored)
```


```{r}
str(bhargav1$Runs.Scored)
```
#Step3: Descriptive Statistics for Categorical Variables

```{r}
table(bhargav1$Captain)
```


```{r}
bhargav1$Captain
```


```{r}
str(bhargav1$Captain)
```
#Step4: Transforming The Variables

```{r}
log(bhargav1$Runs.Scored)
```


```{r}
log(bhargav1$Innings)

```


```{r}
bhargav2<-bhargav1$Strike.Rate- mean(bhargav1$Strike.Rate)/sd(bhargav1$Strike.Rate)
bhargav2
```
#Step5: Plotting the variables

```{r}
hist(bhargav1$Runs.Scored,main = "HISTOGRAM of Runs Scored")
```


```{r}
plot(bhargav1$Century.Number,bhargav1$Runs.Scored,main = "Plot")
```


